#!/usr/bin/env python3
# ==================================================================================================
# BANDO SUITE INSTALLER
#
# VERSION:          v1.2.0-BANDO-GODCORE
#
# PURPOSE:          Facilitates the setup of a virtual environment for Bando Suite applications,
#                   installs necessary dependencies, creates launcher scripts,
#                   and can optionally package them into executables using PyInstaller.
#
# USAGE:            python install_bando_suite_v1.2.0-BANDO-GODCORE.py [--venv VENV_DIR]
#                   [--install-dir INSTALL_DIR] [--package]
#
# CHANGELOG:
#   v1.0.0: Initial release. Basic venv creation and dependency installation.
#   v1.1.0: Added launcher script generation and README creation.
#   v1.2.0: Added --package flag to build executables using PyInstaller.
#           Added PyInstaller to requirements.
#           Updated header and documentation.
#
# ==================================================================================================

import os
import sys
import subprocess
import argparse
import venv
from pathlib import Path

# --- Configuration ---
REQUIREMENTS = [
    "fastapi>=0.100.0", # For bando_copilot_core
    "uvicorn[standard]>=0.20.0", # For bando_copilot_core
    "pydantic>=1.10.0", # For bando_copilot_core
    "cryptography>=38.0.0", # For bando_copilot_core
    "tkinter", # Usually part of standard lib, but good to note for bando_dataset_trainer_gui
    "torch", # Placeholder for bando_dataset_trainer_gui actual ML deps
    "torchvision", # Placeholder
    "sentencepiece", # Placeholder
    "tqdm", # Placeholder
    "pyinstaller>=5.7.0" # For packaging
]

# Names of the core scripts to be managed/packaged
BANDO_COPILOT_SCRIPT = "bando_copilot_core_v1.0.0-BANDO-GODCORE.py"
BANDO_TRAINER_SCRIPT = "bando_dataset_trainer_gui_v1.0.0-BANDO-GODCORE.py"

README_TEMPLATE = """# Bando Suite – Quick Start

This README is generated by the installer.

## 1. Installation

If you haven't already, run the installer:
```bash
python install_bando_suite_v1.2.0-BANDO-GODCORE.py [--venv YOUR_VENV_DIR] [--package] [--auto-launch]
```
*   `--venv YOUR_VENV_DIR`: Specify a custom directory for the virtual environment (default: ./bando_env).
*   `--package`: After installation, package the applications into executables using PyInstaller.
*   `--auto-launch`: Launch the Bando Trainer GUI immediately after installation.

## 2. Activate Virtual Environment

Before running the tools directly or building them, activate the created virtual environment.
The installer created a virtual environment at: `{venv}`

**Linux/macOS:**
```bash
source {venv}/bin/activate
```

**Windows (Command Prompt):**
```bash
{venv}\Scripts\activate.bat
```
**Windows (PowerShell):**
```bash
{venv}\Scripts\Activate.ps1
```

## 3. Launch Tools (Using Launcher Scripts)

Launcher scripts were created in the `./launchers/` directory and a root-level launcher for the trainer was also created.

**From the directory where you ran the installer:**
```bash
# For the Trainer GUI
./start_bando_trainer.sh  # Linux/macOS
# or
.\start_bando_trainer.bat # Windows

# For the Copilot (FastAPI service)
./launchers/bando-copilot.sh # Linux/macOS
# or
.\launchers\bando-copilot.bat  # Windows
```
These scripts automatically use the correct virtual environment.

## 4. Running Packaged Applications (if `--package` was used)

If you used the `--package` flag during installation, standalone executables were created in the `dist/` directory.

*   `dist/bando_trainer/bando_trainer` (or `bando_trainer.exe` on Windows)
*   `dist/bando_copilot/bando_copilot` (or `bando_copilot.exe` on Windows)

You can run these executables directly without activating the virtual environment.

## 5. Manual Packaging (Advanced)

If you want to repackage the applications manually (e.g., after code changes):
1. Ensure PyInstaller is installed in the virtual environment:
   ```bash
   pip install pyinstaller>=5.7.0
   ```
2. Run PyInstaller with the generated spec files (the installer creates these temporarily during the `--package` step, but you can save them or regenerate them):
   ```bash
   # From the root directory of the project
   pyinstaller bando_copilot.spec
   pyinstaller bando_trainer.spec
   ```
   This will build the executables into the `dist/` folder. The `.spec` files (`bando_copilot.spec`, `bando_trainer.spec`) define how the packaging is done. The installer v1.2.0+ can generate these for you if you run it with `--package`.

## Requirements

A `requirements.txt` file was also generated, listing all Python dependencies.
"""

# --- Helper Functions ---

def run(cmd, check=True, env=None):
    """Runs a command and prints its output."""
    print(f"\n[CMD] {' '.join(map(str, cmd))}")
    try:
        process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1, universal_newlines=True, env=env)
        for line in process.stdout:
            print(line, end='')
        process.wait()
        if check and process.returncode != 0:
            raise subprocess.CalledProcessError(process.returncode, cmd)
        return process.returncode
    except Exception as e:
        print(f"[ERROR] Command failed: {e}")
        if check:
            raise
        return 1 # Non-zero return code

def create_venv(venv_dir):
    """Creates a virtual environment."""
    print(f"\n[INFO] Ensuring virtual environment in {venv_dir}...")
    # If the directory exists, EnvBuilder will generally ensure it's a valid venv
    # or update it if necessary (e.g., ensure pip is present).
    # Removing the early exit:
    # if venv_dir.exists():
    #     print("[INFO] Virtual environment directory already exists. Assuming it's functional or will be updated.")
    #     return
    try:
        # upgrade_deps=True will ensure pip, setuptools are up to date.
        builder = venv.EnvBuilder(with_pip=True, upgrade_deps=True, prompt="bando-venv")
        builder.create(str(venv_dir)) # This will create if not exists, or update/ensure if it does.
        print("[INFO] Virtual environment created successfully.")

        print(f"[DEBUG] Contents of {venv_dir}:")
        for item in venv_dir.iterdir(): print(f"  {item.name}")
        print(f"[DEBUG] Contents of {venv_dir / 'bin'}:") # 'bin' is standard on Linux for venv
        bin_dir = venv_dir / ('bin' if os.name != 'nt' else 'Scripts')
        if bin_dir.exists():
            for item in bin_dir.iterdir(): print(f"  {item.name}")
        else:
            print(f"  {bin_dir} does not exist.")
        print(f"[DEBUG] Contents of {venv_dir / 'lib'}:")
        lib_dir = venv_dir / 'lib'
        if lib_dir.exists():
            for item in lib_dir.iterdir(): print(f"  {item.name}")
        else:
            print(f"  {lib_dir} does not exist.")
        # Check for lib64 as well, given the tool error
        lib64_dir = venv_dir / 'lib64'
        if lib64_dir.exists():
            print(f"[DEBUG] Contents of {lib64_dir}:")
            for item in lib64_dir.iterdir(): print(f"  {item.name}")
        else:
            print(f"  {lib64_dir} does not exist or is not a directory viewable this way.")

    except Exception as e:
        print(f"[ERROR] Could not create virtual environment: {e}")
        sys.exit(1)

def get_pip_exec(venv_dir):
    """Gets the pip executable path from the venv."""
    return venv_dir / ("Scripts/pip.exe" if os.name == "nt" else "bin/pip")

def pip_install(venv_dir, packages):
    """Installs packages using pip from the venv."""
    pip_exec = get_pip_exec(venv_dir)
    print(f"\n[INFO] Installing packages using {pip_exec}...")
    if not packages:
        print("[INFO] No packages to install.")
        return
    cmd = [str(pip_exec), "install"] + packages
    run(cmd)
    print("[INFO] Packages installed successfully.")

def write_requirements_file(install_dir, packages):
    """Writes a requirements.txt file."""
    req_file = install_dir / "requirements_installed.txt"
    print(f"\n[INFO] Writing installed requirements to {req_file}...")
    try:
        with open(req_file, "w") as f:
            f.write("# Requirements installed by Bando Suite Installer\n")
            for pkg in packages:
                f.write(pkg + "\n")
        print("[INFO] Requirements file written.")
    except IOError as e:
        print(f"[ERROR] Could not write requirements file: {e}")

def write_readme_file(install_dir, venv_dir):
    """Writes the README_INSTALL.md file based on the template."""
    readme_file = install_dir / "README_INSTALL.md" # New filename
    print(f"\n[INFO] Writing README to {readme_file}...")

    # Ensure venv_dir is an absolute path for clarity in the README
    abs_venv_dir = venv_dir.resolve()
    content = README_TEMPLATE.format(venv=abs_venv_dir)

    try:
        with open(readme_file, "w") as f:
            f.write(content)
        print("[INFO] README file written.")
    except IOError as e:
        print(f"[ERROR] Could not write README file: {e}")

def write_launcher_scripts(install_dir, venv_dir):
    """Creates launcher scripts for the Bando applications."""
    print(f"\n[INFO] Creating launcher scripts in {install_dir}...")
    scripts_to_launch = {
        "bando_copilot_launcher": BANDO_COPILOT_SCRIPT,
        "bando_trainer_launcher": BANDO_TRAINER_SCRIPT
    }

    python_exec = venv_dir / ("Scripts/python.exe" if os.name == "nt" else "bin/python")

    for name, target_script in scripts_to_launch.items():
        if not (Path.cwd() / target_script).exists(): # Assuming target scripts are in CWD with installer
            print(f"[WARNING] Target script {target_script} not found. Skipping launcher for it.")
            continue

        if os.name == "nt":
            launcher_path = install_dir / f"{name}.bat"
            content = f"@echo off\ncall \"{venv_dir}\\Scripts\\activate.bat\"\npython \"%~dp0\\..\\{target_script}\" %*\ndeactivate\n"
            # Assumes target_script is one level up from install_dir if install_dir is a sub-folder
            # For simplicity, let's assume install_dir is where scripts will be copied or run from relative to CWD
            content = f"@echo off\ncall \"{python_exec}\" \"{Path.cwd() / target_script}\" %*\n"

        else: # macOS/Linux
            launcher_path = install_dir / f"{name}.sh"
            content = f"#!/bin/bash\nsource \"{venv_dir}/bin/activate\"\nexec python \"{Path.cwd() / target_script}\" \"$@\"\n"

        try:
            with open(launcher_path, "w") as f:
                f.write(content)
            if os.name != "nt":
                os.chmod(launcher_path, 0o755) # Make executable
            print(f"[INFO] Created launcher: {launcher_path}")
        except IOError as e:
            print(f"[ERROR] Could not write launcher script {launcher_path}: {e}")

# --- Main ---
def main():
    parser = argparse.ArgumentParser(description="Bando Suite Installer")
    parser.add_argument(
        "--venv",
        type=Path,
        default=Path("venv_bando"),
        help="Directory to create the virtual environment in. Default: %(default)s"
    )
    parser.add_argument(
        "--install-dir",
        type=Path,
        default=Path("bando_suite_installed"),
        help="Directory to place launcher scripts and supplementary files. Default: %(default)s"
    )
    parser.add_argument(
        "--package",
        action="store_true",
        help="Package the scripts into executables using PyInstaller after installation."
    )
    args = parser.parse_args()

    venv_dir = args.venv.resolve()
    install_dir = args.install_dir.resolve()

    print("=======================================")
    print("    BANDO SUITE INSTALLER v1.2.0     ")
    print("=======================================")

    # Create directories
    venv_dir.mkdir(parents=True, exist_ok=True)
    install_dir.mkdir(parents=True, exist_ok=True)

    create_venv(venv_dir)
    pip_install(venv_dir, REQUIREMENTS)
    write_requirements_file(install_dir, REQUIREMENTS)
    write_readme_file(install_dir, venv_dir) # Pass venv_dir
    write_launcher_scripts(install_dir, venv_dir) # Launchers placed in install_dir

    if args.package:
        print("\n[INFO] Starting PyInstaller packaging process...")

        # Define spec file contents (as multi-line strings)
        # Note: Hidden imports might need to be adjusted based on actual script dependencies and PyInstaller version
        copilot_spec_content = f"""
# bando_copilot.spec
# -*- mode: python ; coding: utf-8 -*-
block_cipher = None
a = Analysis(
    ['{BANDO_COPILOT_SCRIPT}'],
    pathex=['{Path.cwd()}'], # Ensure script's directory is in pathex
    binaries=[], datas=[],
    hiddenimports=[
        'uvicorn.lifespan.on', 'uvicorn.loops.auto', 'uvicorn.protocols.auto',
        'uvicorn.protocols.http.auto', 'uvicorn.protocols.websockets.auto',
        'uvicorn.logging', 'fastapi.applications', 'fastapi.routing',
        'starlette.routing', 'starlette.applications', 'cryptography',
        'asyncio' # Common hidden import for uvicorn/fastapi
    ],
    hookspath=[], hooksconfig={{}}, runtime_hooks=[], excludes=[],
    win_no_prefer_redirects=False, win_private_assemblies=False,
    cipher=block_cipher, noarchive=False
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz, a.scripts, [], exclude_binaries=True, name='bando_copilot',
    debug=False, bootloader_ignore_signals=False, strip=False, upx=True,
    console=True, disable_windowed_traceback=False, argv_emulation=False,
    target_arch=None, codesign_identity=None, entitlements_file=None
)
coll = COLLECT(
    exe, a.binaries, a.zipfiles, a.datas, strip=False, upx=True,
    upx_exclude=[], name='bando_copilot'
)
"""
        trainer_spec_content = f"""
# bando_trainer.spec
# -*- mode: python ; coding: utf-8 -*-
block_cipher = None
a = Analysis(
    ['{BANDO_TRAINER_SCRIPT}'],
    pathex=['{Path.cwd()}'], # Ensure script's directory is in pathex
    binaries=[], datas=[],
    hiddenimports=[
        'torch', 'torch.nn', 'torch.optim', 'torch.utils', 'torch.utils.data',
        'torchvision', 'tkinter.filedialog', 'tkinter.messagebox', 'tkinter.ttk',
        'sentencepiece', 'tqdm', 'threading' # threading was used in GUI
    ],
    hookspath=[], hooksconfig={{}}, runtime_hooks=[], excludes=[],
    win_no_prefer_redirects=False, win_private_assemblies=False,
    cipher=block_cipher, noarchive=False
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz, a.scripts, [], exclude_binaries=True, name='bando_trainer',
    debug=False, bootloader_ignore_signals=False, strip=False, upx=True,
    console=False, disable_windowed_traceback=False, argv_emulation=False, # console=False for GUI
    target_arch=None, codesign_identity=None, entitlements_file=None
)
coll = COLLECT(
    exe, a.binaries, a.zipfiles, a.datas, strip=False, upx=True,
    upx_exclude=[], name='bando_trainer'
)
"""
        # Write spec files to CWD, as PyInstaller runs best from there
        copilot_spec_file = Path.cwd() / "bando_copilot.spec"
        trainer_spec_file = Path.cwd() / "bando_trainer.spec"
        try:
            copilot_spec_file.write_text(copilot_spec_content)
            trainer_spec_file.write_text(trainer_spec_content)
            print("[INFO] Generated PyInstaller spec files in current directory.")
        except IOError as e:
            print(f"[ERROR] Could not write spec files: {e}")
            sys.exit(1)

        # Determine PyInstaller path from venv
        pyinstaller_exec = venv_dir / ("Scripts/pyinstaller.exe" if os.name == "nt" else "bin/pyinstaller")

        packaging_env = os.environ.copy()
        # PyInstaller needs to find Python from the venv
        if os.name == 'nt':
            packaging_env['PATH'] = f"{venv_dir / 'Scripts'};{packaging_env.get('PATH', '')}"
        else:
            packaging_env['PATH'] = f"{venv_dir / 'bin'}:{packaging_env.get('PATH', '')}"


        # Run PyInstaller for bando_copilot
        print("\n[INFO] Packaging bando_copilot...")
        try:
            # Run PyInstaller from the directory containing the spec file and script (CWD)
            run([str(pyinstaller_exec), "--noconfirm", str(copilot_spec_file.name)], env=packaging_env, check=True)
            print("[INFO] bando_copilot packaging complete. Output in dist/bando_copilot")
        except subprocess.CalledProcessError as e:
            print(f"[ERROR] bando_copilot packaging failed: {e}")
        except FileNotFoundError:
            print(f"[ERROR] PyInstaller not found at {pyinstaller_exec}. Make sure it's installed in the venv.")
        except Exception as e:
            print(f"[ERROR] An unexpected error occurred during bando_copilot packaging: {e}")


        # Run PyInstaller for bando_trainer
        print("\n[INFO] Packaging bando_trainer...")
        try:
            run([str(pyinstaller_exec), "--noconfirm", str(trainer_spec_file.name)], env=packaging_env, check=True)
            print("[INFO] bando_trainer packaging complete. Output in dist/bando_trainer")
        except subprocess.CalledProcessError as e:
            print(f"[ERROR] bando_trainer packaging failed: {e}")
        except FileNotFoundError:
            print(f"[ERROR] PyInstaller not found at {pyinstaller_exec}. Make sure it's installed in the venv.")
        except Exception as e:
            print(f"[ERROR] An unexpected error occurred during bando_trainer packaging: {e}")


        # Clean up spec files
        print("[INFO] Cleaning up spec files...")
        if copilot_spec_file.exists(): copilot_spec_file.unlink()
        if trainer_spec_file.exists(): trainer_spec_file.unlink()
        print("\n[INFO] PyInstaller packaging process finished.")

    print("\n=======================================")
    print(" Bando Suite Installation Complete!  ")
    print(f" Venv: {venv_dir}")
    print(f" Install Dir: {install_dir}")
    if args.package:
        print(f" Packaged executables in: {Path.cwd() / 'dist'}")
    print("=======================================")

if __name__ == "__main__":
    main()
