import os

class ASIConfigCore:
    DIMENSIONS = 128
    ATTENTION_MAX_DEPTH = 3
    MEMORY_RETENTION_THRESHOLD = 0.05
    MAX_CONTEXT_WINDOW = 10
    MAX_TOKENIZER_KEYWORDS = 3
    PULSE_LOG_MAXLEN = 100
    PLUGIN_DIR = "victor_plugins"  # Adjusted to match plan
    MIN_EMOTIONAL_RELEVANCE = 0.25
    CONCEPT_INDUCTION_THRESHOLD = 3
    CONCEPT_SIMILARITY_THRESHOLD = 0.65
    TOKENIZER_DIR = "victor_tokenizers"
